# Generated by Django 3.2.18 on 2023-05-09 08:04

import apps.payments.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Name')),
                ('code', models.CharField(help_text='example: USD', max_length=3, verbose_name='Code')),
                ('symbol', models.CharField(blank=True, help_text='example: $', max_length=3, null=True, verbose_name='Symbol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PayPal', 'PayPal'), ('Stripe', 'Stripe')], max_length=16, unique=True, verbose_name='Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Icon')),
                ('active', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, null=True, unique=True)),
                ('description', models.TextField(help_text='Enter items separated by comma', max_length=2048)),
                ('price', models.PositiveSmallIntegerField(help_text='Euro(€)')),
                ('limit', models.PositiveSmallIntegerField(default=0, help_text='Maximum identification limit per month, for this plan', verbose_name='Identification Limit')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.currency')),
            ],
            options={
                'verbose_name': 'Price Plan',
                'verbose_name_plural': 'Price Plans',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.PositiveIntegerField(default=apps.payments.models.generate_invoice_id, verbose_name='Invoice ID')),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ref ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.gateway', verbose_name='Payment Gateway')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.plan', verbose_name='Price Plan')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
