"""
Django settings for identipo project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w64wz+*^**4#7q2tfjff#jl+zkf-q_zgjf(4fq1h0hwo7j)wxe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    # 'admin_tools_stats',
    # 'django_nvd3',
    'jazzmin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'django.contrib.sites',
    'django.contrib.staticfiles',
    'django_extensions',
    'webcampicture',
    'django_countries',
    'apps.dashboard',
    'apps.limited',
    'apps.pages',
    'apps.payments',
    'apps.reports',
    'apps.support',
    'apps.users',
    'apps.verification',
    'apps.web',
    'django.contrib.admin',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'identipo.middlewares.RestrictStaffToAdminMiddleware',
    'identipo.middlewares.RestrictSuperuserToDashboardMiddleware'
]

ROOT_URLCONF = 'identipo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'reports': 'apps.dashboard.templatetags.reports',
                'plans': 'apps.web.templatetags.plans',

            }
        },

    },
]

WSGI_APPLICATION = 'identipo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         # 'ENGINE': 'django.db.backends.sqlite3',
#         # 'NAME': BASE_DIR / 'db.sqlite3',
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': "railway",
#         'USER': "postgres",
#         'PASSWORD': "ktdxl54WNSgEpyVgcOsy",
#         'HOST': "containers-us-west-23.railway.app",
#         'PORT': 7725,
#     }
# }

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': "identipo",
        'USER': "identipo",
        'PASSWORD': "eRr5Ydhd9MER0pqq0vcr",
        'HOST': "identipocom-3193.postgres.pythonanywhere-services.com",
        'PORT': 13193,
    }
}

# enter here your database credentials

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATICFILES_FINDERS = [
#     'django.contrib.staticfiles.finders.FileSystemFinder',
#     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
# ]
#
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = f'https://s3.eu-central-1.wasabisys.com/{AWS_STORAGE_BUCKET_NAME}/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

SECURE_SSL_REDIRECT = False

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# EMAIL_SSL_CERTFILE = None
# EMAIL_SSL_KEYFILE = None
# EMAIL_TIMEOUT = None

EMAIL_HOST = 'smtp.zoho.eu'
# EMAIL_HOST_USER = 'freelancer7rg@gmail.com'
# EMAIL_HOST_PASSWORD = '8597E7503E23074FAD989873964D9A605EA1'
EMAIL_HOST_USER = 'info@identipo.com'
EMAIL_HOST_PASSWORD = 'Thomadek1956####'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_USE_SSL = True
EMAIL_SEND_DOMAIN = 'https://www.identipo.com'

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

JAZZMIN_SETTINGS = {
    "site_title": "Identipo",
    "site_header": "Identipo",
    "site_brand": "Identipo",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "/web/images/favicon.png",
    #
    # # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "web/images/logo3.png",
    #
    # # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": "web/images/logo3.png",
    #
    # CSS classes that are applied to the logo above
    "site_logo_classes": None,
    #
    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    "welcome_sign": " ",
    "copyright": "Identipo",
    "search_model": ["users.User", ],
    "user_avatar": 'picture',

    # ############
    # # Top Menu #
    # ############
    #
    # # Links to put along the top menu
    "topmenu_links": [
        {"name": "Home", "url": "web:home", "permissions": []},

        # # external url that opens in a new window (Permissions can be added)
        # {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

        # # model admin to link to (Permissions checked against model)
        # {"model": "users.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        # {"app": "payments"},
    ],
    #
    # #############
    # # User Menu #
    # #############
    #
    # # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Support", "url": "dashboard_admin:dashboard_ticket_changelist"},
        {"model": "auth.user"}
    ],
    #
    # #############
    # # Side Menu #
    # #############
    "show_sidebar": True,
    "navigation_expanded": True,
    # "hide_apps": [],
    "hide_models": ["dashboard.Profile"],
    #
    # # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": [

        "users",
        "auth",

        "users.User",
        "users.Identity",
        "users.Company",
        "users.Country",
        "dashboard",
        "dashboard.Customer",
        "dashboard.Employee",
        "dashboard.MyPlan",
        "dashboard.MyPayment",
        "dashboard.Report",
        "dashboard.Ticket",
        "Profile",
        "Security",

        "payments",
        "payments.Plan",
        "payments.Gateway",
        "payments.Payment",
        "pages.Page",
        "payments.Payment",

        "pages",

        "support",

        # "My Plans",
        # "My Payments",
    ],

    "icons": {
        "users.User": "fas fa-user",
        "users.Identity": "fas fa-fingerprint",
        "users.Company": "fas fa-building",
        "users.Country": "fas fa-globe",
        "web.SiteSetting": "fas fa-wrench",
        "payments": "fas fa-fingerprint",
        "payments.Plan": "fas fa-cube",
        "payments.Payment": "fas fa-credit-card",
        "payments.Gateway": "fas fa-door-open",
        "payments.Currency": "fas fa-dollar-sign",
        "auth.Group": "fas fa-users",
        "auth": "fas fa-users-cog",
        "support.Ticket": "fas fa-headset",
        "pages.Page": "fas fa-newspaper",
        "preferences.Preferences": "fas fa-headset",
        "dashboard.Customer": "fas fa-users",
        "dashboard.Employee": "fas fa-users",
        "dashboard.MyPlan": "fas fa-cube",
        "dashboard.MyPayment": "fas fa-credit-card",
        "dashboard.Report": "fas fa-chart-bar",
        "dashboard.Ticket": "fas fa-headset",
        "dashboard.MyIdentity": "fas fa-fingerprint",
    },
    #
    # # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "admin": [
            {
                "name": "Profile",
                "url": "dashboard:my_profile",
                "icon": "fas fa-address-card",
                "permissions": []
            },
        ],
        "dashboard": [
            {
                "name": "Profile",
                "url": "dashboard:my_profile",
                "icon": "fas fa-address-card",
                "permissions": []
            },
            # {
            #     "name": "Reports",
            #     "url": "/dashboard/dashboard/reports/",
            #     "icon": "fas fa-chart-bar",
            #     "permissions": []
            # },
            {
                "name": "Security",
                "url": "dashboard:security",
                "icon": "fas fa-lock",
                "permissions": []
            },
            {
                "name": "Settings",
                "url": "dashboard:setting",
                "icon": "fas fa-wrench",
                "permissions": []
            }

        ],
        "limited": [
            {
                "name": "Limited",
                "url": "make_messages",
                "icon": "fas fa-comments",
                "permissions": []
            },
        ]
    },
    #
    # # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    #
    # #################
    # # Related Modal #
    # #################
    # # Use modals instead of popups
    "related_modal_active": True,
    #
    # #############
    # # UI Tweaks #
    # #############
    # # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": "web/css/dashboard.css",
    "custom_js": "web/js/dashboard.js",
    # # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    # "use_google_fonts_cdn": True,
    # # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,
    #
    # ###############
    # # Change view #
    # ###############
    # # Render out the change view as a single form, or in tabs, current options are
    # # - single
    # # - horizontal_tabs (default)
    # # - vertical_tabs
    # # - collapsible
    # # - carousel
    "changeform_format": "horizontal_tabs",
    # # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"dashboard.Customer": "single"},
}

STRIPE_PUBLIC_KEY = "pk_test_51N9CS5FHOKb56fHQSbQQA0pBReR3kgHUEJwKlJwQB6kEtEdig4O6DmbQgBaoBgRFQq6WlbTiOVeJzNuTHFhvYaIg00zrVYIiqX"
STRIPE_SECRET_KEY = "sk_test_51N9CS5FHOKb56fHQvmByjitu5MaPSTog4Ox4gLnUFat9iQqC0vFz8PkDtts3sSStToKxUjjoje9CjXhonDyqbwG5008BKFiwcZ"

# ///////////////////////////////paypal//////////////////

import paypalrestsdk

paypalrestsdk.configure({
    "mode": "sandbox",  # Use 'live' for production environment
    "client_id": 'AWvcBY6zcCs64FMvs53u4Y77qPcmxBYsjvJFIhYDrcEvZCpV49CjHuBaXGma-mrrQfG6OxlPTNhCuQfa',
    "client_secret": 'ENmY3an9ZYWbIyR1_ItCXx8yErZ2XIWylZFQys7EjKfdmg__TD9XyqDC-o6HedDCd5tmmxeeT9HL8S7-',
})

# ///////////////////////////////Paystack//////////////////////////////////////////
PAYSTACK_PUBLIC_KEY = 'your_paystack_public_key'
PAYSTACK_SECRET_KEY = 'your_paystack_secret_key'

