# Generated by Django 3.2.18 on 2023-05-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('text', models.TextField(max_length=256, verbose_name='Text')),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='New', max_length=16, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Helpdesk',
            },
        ),
    ]
