# Generated by Django 3.2.18 on 2023-05-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Contains only small letters and hyphen. Example: terms-and-conditions', max_length=32, verbose_name='Slug')),
                ('header', models.CharField(max_length=64, verbose_name='Header')),
                ('content', models.TextField(max_length=4096, verbose_name='Content')),
                ('seo_text', models.TextField(max_length=4096, verbose_name='SEO Text')),
                ('link_position', models.CharField(choices=[('Header', 'Header'), ('Footer', 'Footer')], default='Footer', max_length=16, verbose_name='Link Position')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
